var member = [
  {
    "phone": "No.1",
    "name": "张力"
  },{
    "phone": "No.2",
    "name": "梁行"
  },      {
    "phone": "No.3",
    "name": "赵向前"
  },      {
    "phone": "No.4",
    "name": "黄伟"
  },      {
    "phone": "No.5",
    "name": "于志君"
  },      {
    "phone": "No.6",
    "name": "贾文文"
  },      {
    "phone": "No.7",
    "name": "王宾"
  },      {
    "phone": "No.8",
    "name": "杨宇霆"
  },      {
    "phone": "No.9",
    "name": "张记"
  },      {
    "phone": "No.10",
    "name": "李景慧"
  },      {
    "phone": "No.11",
    "name": "洪子璇"
  },      {
    "phone": "No.12",
    "name": "王先冉"
  },      {
    "phone": "No.13",
    "name": "刘刚锋"
  },      {
    "phone": "No.14",
    "name": "刘金龙"
  },      {
    "phone": "No.15",
    "name": "贺佳坤"
  },      {
    "phone": "No.16",
    "name": "郑海洋"
  },      {
    "phone": "No.17",
    "name": "曹猛"
  },      {
    "phone": "No.18",
    "name": "徐昆"
  },      {
    "phone": "No.19",
    "name": "吕聪聪"
  },      {
    "phone": "No.20",
    "name": "崔永才"
  },      {
    "phone": "No.21",
    "name": "秦世明，"
  },      {
    "phone": "No.22",
    "name": "于光远"
  }
]